---
- name: Install mysql
  yum: name=mysql,mysql-server,mysql-tuner state=present

#later on: set up replication?

- name: Set up iptables rules
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql
