---
- name: Install apache
  yum: name=httpd state=present

# Install this module with a static rpm file
- name: Install mod_fastcgi from rpm
  rpm: name=mod_fastcgi-2.4.6-2.el6.rf.x86_64.rpm state=present
  notify: mod_fastcgi config

- name: Install mod_ssl
  yum: name=mod_ssl state=present
  notify: mod_ssl config

- name: restart the server now that configs are in place
  notify: restart apache
