---
 - name: Install named
   yum: name=bind,bind-utils,bind-chroot state=present
#   notify: 
#   - named.conf config
#   - aggroskater.com config
 - name: Get initial named.conf config set up
   template: src=named.conf.j2 dest=/var/named/chroot/etc/named.conf
 - name: Get aggroskater.com zone set up
   template: src=aggroskater.com.db.j2 dest=/var/named/chroot/var/named/aggroskater.com.db
 - name: Adjust perms in chroot
   file: path=/var/named/chroot/var/named owner=named group=named recurse=yes
 - name: restart bind
   service: name=named state=restarted
