---
# lamp stack
- name: Linux, Apache, PHP portion (maybe varnish too)
  hosts: vagrantbox.com
  roles:
  - common
  - named
  - php-fpm
  - apache
#  - wordpress

- name: DB portion
  hosts: vagrantbox-db.com
  roles:
  - mysql # master
#  - replication
#  - memcached
#  - redis
