---
# lamp stack
- name: Linux, Apache, PHP portion (maybe varnish too)
  hosts: vagrantbox.com
  roles:
  - common
  - named
  - php-fpm
#  - php-modules
#  - memcached
  - apache
#  - wordpress

- name: DB portion
  hosts: vagrantbox-db.com
  roles:
  - mysql
